name: bartermade
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^0.3.4+1
  dropdown_date_picker: ^0.1.1+2
  cupertino_icons: ^1.0.2
  flutter_verification_code: ^1.0.3
  decorative_app_bar: ^0.0.2
  custom_switch: ^0.0.1
  custom_switch_button: ^0.5.0
  carousel_slider: ^1.3.0
  flutter_carousel_slider: ^1.0.8
  auto_orientation: ^2.0.2
  provider: ^6.0.1
  http: ^0.13.4
  flushbar: ^1.10.4
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
   - assets/icons/
   - assets/images/
fonts:
    - family: FiraMono
      fonts:
        - assets: fonts/FiraMono-Bold.ttf
          weight: 700
        - assets: fonts/FiraMono-Regular.ttf
    - family: IBMPlexSans
      fonts:
        - assets: fonts/IBMPlexSans-Bold.ttf
          weight: 700

        - assets: fonts/IBMPlexSans-Italic.ttf
          weight: 700
